server:
  port: 4000
eureka:
  instance:
    hostname: eurake.bugod.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/