server:
  port: 4001
  compression:
    enabled: true
    min-response-size: 10
    excluded-user-agents: gozilla,traviata
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  application:
    name: base-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:4010

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    max-history: 10
    max-size: 100MB
    name: ./${spring.application.name}/log/${spring.application.name}.log
  level:
    root: info
    org.springframework: info
    com.bugod.core.mapper*: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:sss} [%thread|%X{API_TRACE_ID}] %-5level %logger{10} - %msg%n'
    console: '%red(%d{yyyy-MM-dd HH:mm:sss}) %green([%thread|%X{API_TRACE_ID}]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'