spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bugod?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;
      use-global-data-source-stat: true
    monitor:
      allow: 192.168.22.251
      loginUsername: druid
      loginPassword: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  mybatis-plus:
    type-aliases-package: com.bugod.entity
  global-config:
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    sql-parser-cache: false
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: false
