server:
  port: 4001
  compression:
    enabled: true
    min-response-size: 10
    excluded-user-agents: gozilla,traviata
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  application:
    name: base-service
  profiles:
    active: dev

logging:
  file:
    max-history: 10
    max-size: 100MB
    name: ./${spring.application.name}/log/${spring.application.name}.log
  level:
    root: info
    org.springframework: info
    com.bugod.core.mapper*: info
  pattern:
  #  file: [%date{yyyy-MM-dd HH:mm:ss}][%thread][%-5level] %c{40} %line --%mdc{client} [%X{API_TRACE_ID}] %msg%n
    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread|%X{API_TRACE_ID}]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
